name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Testing
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v3
      with:
        version: 8
        run_install: |
          - recursive: true

    - name: Check Types
      run: pnpm run typecheck
      
    - name: Run Tests
      run: pnpm run test

  # Deploy docs
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: "Deploy Docs"
        run: cd website && pnpm install && pnpm run deploy
        env:
          GIT_USER: Neo-Ciber94
