name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  # Testing
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true

      - name: Check Types
        run: pnpm run typecheck # FIXME: this fails with src/components/LiveExample.tsx(3,24): error TS2307: Cannot find module 'seria' or its corresponding type declarations.

      - name: Check formatting
        run: pnpm run lint

      - name: Run Tests
        run: pnpm run test

  # Deploy docs
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            website:
              - 'website/**'

      - name: Build Docs
        if: steps.changes.outputs.website == 'true'
        run: cd website && pnpm install && pnpm run build

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        if: steps.changes.outputs.website == 'true' && github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
