name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Testing
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true

      - name: Check Types
        run: pnpm run typecheck

      - name: Run Tests
        run: pnpm run test

  # Deploy docs
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set git config
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: "Deploy Docs"
        run: cd website && pnpm install && pnpm run deploy
        env:
          GIT_USER: github-actions[bot]
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
